Vagrant.configure("2") do |config|

  # Box file settings
  # ------------------------------

  config.vm.box = "CentOS-6.4.x86_64"
  config.vm.box_url = "../../boxes/CentOS-6.4.x86_64.box"
  config.vm.synced_folder "../../share", "/share"

  # Global VM settings
  # ------------------------------

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Puppet provisioning
  # ------------------------------

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../../puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = ["../../puppet/vendor","../../puppet/modules"]
  end

  # alpha VM
  # ------------------------------

  config.vm.define "alpha" do |alpha|
    alpha.vm.network :private_network, ip: "192.168.33.10"
    alpha.vm.hostname = "alpha"
  end

  # bravo VM
  # ------------------------------

  config.vm.define "bravo" do |bravo|
    bravo.vm.network :private_network, ip: "192.168.33.11"
    bravo.vm.hostname = "bravo"
  end

  # gamma VM
  # ------------------------------

  # config.vm.define "gamma" do |gamma|
  #   gamma.vm.network :private_network, ip: "192.168.33.12"
  #   gamma.vm.hostname = "gamma"
  # end

  # delta VM
  # ------------------------------

  # config.vm.define "delta" do |delta|
  #   delta.vm.network :private_network, ip: "192.168.33.13"
  #   delta.vm.hostname = "delta"
  # end

  # epsilon VM
  # ------------------------------

  # config.vm.define "epsilon" do |epsilon|
  #   epsilon.vm.network :private_network, ip: "192.168.33.14"
  #   epsilon.vm.hostname = "epsilon"
  # end

  # zeta VM
  # ------------------------------

  # config.vm.define "zeta" do |zeta|
  #   zeta.vm.network :private_network, ip: "192.168.33.15"
  #   zeta.vm.hostname = "zeta"
  # end

  # eta VM
  # ------------------------------

  # config.vm.define "eta" do |eta|
  #   eta.vm.network :private_network, ip: "192.168.33.16"
  #   eta.vm.hostname = "eta"
  # end

  # theta VM
  # ------------------------------

  # config.vm.define "theta" do |theta|
  #   theta.vm.network :private_network, ip: "192.168.33.17"
  #   theta.vm.hostname = "theta"
  # end

end
